version: '3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - "discovery.type=single-node"
      - "cluster.name=docker-cluster"
    ports:
      - "9200:9200"
    networks:
      - de-master
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - /Users/vrams/master/82-Hands-on/04-Data-Engineering/de-master/ELK/logstash.conf.yaml:/usr/share/logstash/pipeline/logstash.conf
  

    depends_on:
      - elasticsearch
    networks:
      - de-master
    environment:
      - LS_JAVA_OPTS=-Xmx1g -Xms1g

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - de-master
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

networks:
  de-master:
    name: de-master
    driver: bridge

volumes:
  elasticsearch-data:
